name: Deploy on Dev Push

on:
  push:
    branches:
      - dev

jobs:
  build-and-run-in-runner:
    name: Build and Run Container
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        

      - name: Make deploy script executable
        run: chmod +x deploy.sh

      - name: Execute deployment script
        run: ./deploy.sh


      - name: Waitinf for container to start
        run: |
          echo "Waiting for 10 seconds for the container to start..."
          sleep 10

      - name: Verify container is running
        run: |
          curl -f http://localhost:3000/health || exit 1
          docker ps